### ISSUE TITLE
ipv6出现重复“本地 locations.json 已存在,无需重新下载”的问题

### ISSUE THREAD

**Issue by zzz6839** [cmliu/CFnat-Docker#7]
仅在ipv6下会出现该问题（此前正常运行一个星期没有问题），切换成ipv4不会。该问题会导致节点完全无法使用，调整有效延迟依然会出现“未发现有效IP”

配置：
```
version: '3'

services:
  cfnat:
    container_name: mycfnat
    image: cmliu/cfnat:latest
    environment:
      - colo=HKG # 筛选数据中心例如 HKG,SJC,LAX.电信/联通 推荐 SJC,LAX.移动/广电 推荐 HKG"
      - delay=200  # 有效延迟（毫秒），超过此延迟将断开连接
      - ips=6  # 指定生成IPv4还是IPv6地址
      - port=443  # 转发的目标端口
      - tls=true  # 是否为 TLS 端口
      - random=true  # 是否随机生成IP，如果为false，则从CIDR中拆分出所有IP
      - ipnum=10  # 提取的有效IP数量
      - num=10  # 目标负载 IP 数量
      - task=100  # 并发请求最大协程数
      - code=200  # HTTP/HTTPS 响应状态码
      - domain=cloudflaremirrors.com/debian # 响应状态码检查的域名地址
    ports:
      - "1234:1234"  # 将主机的 1234 端口映射到容器的 1234 端口
    restart: always
```
日志：

```
2024/11/25 10:24:17 正在监听 0.0.0.0:1234 并转发到 10 个目标地址，有效延迟：200 ms
本地 locations.json 已存在,无需重新下载
未发现有效IP总数: 633 已完成: 93.21%
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 99.84%
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
未发现有效IP总数: 633 已完成: 99.84%
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
未发现有效IP总数: 633 已完成: 99.68%
已完成: 633 总数: 633 已完成: 99.84%
已完成: 633 总数: 633 已完成: 99.68%
已完成: 633 总数: 633 已完成: 100.00%
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
本地 locations.json 已存在,无需重新下载
已完成: 633 总数: 633 已完成: 100.00%
未发现有效IP
```
